# =================================================================
# PDF to Audio Converter - Configuration Template
# =================================================================
# Copy this file to config.yaml and customize for your deployment
# config.yaml is gitignored for security

# =================================================================
# APPLICATION SETTINGS
# =================================================================
app:
  name: "PDF to Audio Converter"
  debug: true
  host: "127.0.0.1"  # Secure default: localhost only. Use "0.0.0.0" for network access (development only!)
  port: 5000

# =================================================================
# SECRETS (Keep these secure!)
# =================================================================
secrets:
  # Your Google AI API key (required for LLM text cleaning only - TTS is local)
  # Get yours at: https://aistudio.google.com/app/apikey
  google_ai_api_key: "YOUR_GOOGLE_AI_API_KEY"  # Fill this in your config.yaml

# =================================================================
# TEXT-TO-SPEECH CONFIGURATION (Piper Local Engine)
# =================================================================
tts:
  # Piper TTS Settings (local engine - unlimited processing)
  piper:
    # Available models:
    # US Male: en_US-ryan-high, en_US-ryan-medium
    # GB Female: en_GB-cori-high, en_GB-alba-medium
    model_name: "en_US-ryan-high"
    models_dir: "piper_models"
    length_scale: 1.0  # Speech speed (0.5-2.0)
    model_repository_url: "https://huggingface.co/rhasspy/piper-voices/resolve/main"

# =================================================================
# LLM CONFIGURATION (for text cleaning)
# =================================================================
llm:
  # LLM model for text cleaning and processing (NOT for TTS)
  # Use regular Gemini models (no -tts suffix)
  model_name: "gemini-2.5-pro"

# =================================================================
# TEXT PROCESSING
# =================================================================
text_processing:
  # Enable LLM-powered text cleaning (requires google_ai_api_key)
  enable_text_cleaning: true

  # Enable natural formatting for better narration (dots, pauses)
  enable_natural_formatting: true

  # Text processing chunk sizes
  chunk_size: 4000
  llm_max_chunk_size: 100000
  audio_target_chunk_size: 4000  # Optimal for natural speech generation
  audio_max_chunk_size: 6000     # Maximum before forced split

# =================================================================
# PERFORMANCE SETTINGS
# =================================================================
performance:
  enable_async_audio: true
  max_concurrent_tts_requests: 8  # Local TTS supports higher concurrency
  max_concurrent_requests: 4

# =================================================================
# FILE HANDLING
# =================================================================
files:
  # Upload settings
  upload_folder: "uploads"
  audio_folder: "audio_outputs"
  max_file_size_mb: 20  # Reduced for free service
  allowed_extensions: ["pdf"]
  audio_extensions: ["wav", "mp3"]

  # Storage settings
  local_storage_dir: ".local"

  # Automatic cleanup
  cleanup:
    enabled: true
    max_file_age_hours: 24.0
    auto_cleanup_interval_hours: 6.0
    max_disk_usage_mb: 500  # Reduced for free service

# =================================================================
# OCR SETTINGS
# =================================================================
ocr:
  language: "eng"  # Tesseract language code
  dpi: 300
  threshold: 180
  timeout_seconds: 30

# =================================================================
# AUDIO PROCESSING
# =================================================================
audio:
  concurrent_chunks: 8  # Local TTS processing supports higher concurrency
  bitrate: "128k"
  sample_rate: 22050
  mp3_codec: "libmp3lame"

# =================================================================
# TIMEOUTS
# =================================================================
timeouts:
  tts_seconds: 60
  ffmpeg_seconds: 300

# =================================================================
# RATE LIMITING (for free service)
# =================================================================
rate_limits:
  requests_per_minute: 5
  requests_per_hour: 50
  max_file_size_per_hour_mb: 100

# =================================================================
# CONFIGURATION NOTES
# =================================================================
#
# ARCHITECTURE OVERVIEW:
# - LLM (Gemini): For text cleaning only - uses regular Gemini models
# - TTS (Piper): For audio generation only - local processing, no API needed
#
# PIPER VOICE OPTIONS:
# - en_US-ryan-high/medium: US Male voice
# - en_GB-cori-high: GB Female voice
# - en_GB-alba-medium: GB Female voice
#
# PIPER BENEFITS:
# - Fast, local processing (no API costs)
# - Unlimited concurrent processing
# - Natural speech with punctuation-based pausing
# - No rate limiting or quota restrictions
#
# SIMPLIFIED ARCHITECTURE:
# - Single consistent voice throughout document (no persona switching)
# - Shared TextSegmenter utilities for universal text processing
# - Local processing optimizations (higher concurrency, audio formats)
