# =================================================================
# PDF to Audio Converter - Configuration Template
# =================================================================
# Copy this file to config.yaml and customize for your deployment
# config.yaml is gitignored for security

# =================================================================
# APPLICATION SETTINGS
# =================================================================
app:
  name: "PDF to Audio Converter"
  debug: true
  host: "0.0.0.0"
  port: 5000

# =================================================================
# SECRETS (Keep these secure!)
# =================================================================
secrets:
  # Your Google AI API key (required for Gemini TTS and text cleaning)
  # Get yours at: https://aistudio.google.com/app/apikey
  google_ai_api_key: "YOUR_GOOGLE_AI_API_KEY"  # Fill this in your config.yaml

# =================================================================
# TEXT-TO-SPEECH CONFIGURATION
# =================================================================
tts:
  # Choose: 'piper' (local, fast, no API key) or 'gemini' (cloud, high quality)
  engine: "piper"
  
  # Piper TTS Settings (local engine)
  piper:
    # Available models:
    # US Male: en_US-ryan-high, en_US-ryan-medium
    # GB Female: en_GB-cori-high, en_GB-alba-medium
    model_name: "en_US-ryan-high"
    models_dir: "piper_models"
    length_scale: 1.0  # Speech speed (0.5-2.0)
    model_repository_url: "https://huggingface.co/rhasspy/piper-voices/resolve/main"
  
  # Gemini TTS Settings (cloud engine)
  gemini:
    # TTS-specific model (has -tts suffix, different from LLM model)
    model_name: "gemini-2.5-pro-preview-tts"
    voice_name: "Kore"  # Single consistent voice: Kore, Charon, Aoede, Leda
    
    # Rate limiting optimized for Gemini TTS limits (10 RPM)
    min_request_interval: 6.5  # Seconds between requests (optimized for 10 RPM)
    max_concurrent_requests: 2  # Optimal concurrency for rate limits
    requests_per_minute: 10  # Official Gemini TTS rate limit
    chunk_size_multiplier: 2.0  # Increase chunk sizes for efficiency
    
    # Advanced timing settings  
    use_measurement_mode: false  # Precise timing (slower)
    measurement_mode_interval: 0.8

# =================================================================
# LLM CONFIGURATION (for text cleaning)
# =================================================================
llm:
  # LLM model for text cleaning and processing (NOT for TTS)
  # Use regular Gemini models (no -tts suffix)
  model_name: "gemini-2.5-pro"

# =================================================================
# TEXT PROCESSING
# =================================================================
text_processing:
  # Document type (used by text processing pipeline, ignored by TTS for natural speech)
  document_type: "research_paper"  # research_paper, literature_review, general
  
  # Enable LLM-powered text cleaning (requires google_ai_api_key)
  enable_text_cleaning: true
  
  # Enable advanced SSML markup for better narration
  enable_ssml: true
  
  # Text processing chunk sizes
  chunk_size: 4000
  llm_max_chunk_size: 100000
  audio_target_chunk_size: 4000  # Increased for Gemini efficiency (fewer requests)
  audio_max_chunk_size: 6000  # Increased for Gemini efficiency

# =================================================================
# PERFORMANCE SETTINGS
# =================================================================
performance:
  enable_async_audio: true
  max_concurrent_tts_requests: 2  # Optimized for Gemini 10 RPM limits
  max_concurrent_requests: 4

# =================================================================
# FILE HANDLING
# =================================================================
files:
  # Upload settings
  upload_folder: "uploads"
  audio_folder: "audio_outputs"
  max_file_size_mb: 20  # Reduced for free service
  allowed_extensions: ["pdf"]
  audio_extensions: ["wav", "mp3"]
  
  # Storage settings
  local_storage_dir: ".local"
  
  # Automatic cleanup
  cleanup:
    enabled: true
    max_file_age_hours: 24.0
    auto_cleanup_interval_hours: 6.0
    max_disk_usage_mb: 500  # Reduced for free service

# =================================================================
# OCR SETTINGS
# =================================================================
ocr:
  language: "eng"  # Tesseract language code
  dpi: 300
  threshold: 180
  timeout_seconds: 30

# =================================================================
# AUDIO PROCESSING
# =================================================================
audio:
  bitrate: "128k"
  sample_rate: 22050
  mp3_codec: "libmp3lame"

# =================================================================
# TIMEOUTS
# =================================================================
timeouts:
  tts_seconds: 60
  ffmpeg_seconds: 300

# =================================================================
# RATE LIMITING (for free service)
# =================================================================
rate_limits:
  requests_per_minute: 5
  requests_per_hour: 50
  max_file_size_per_hour_mb: 100

# =================================================================
# CONFIGURATION NOTES
# =================================================================
# 
# IMPORTANT MODEL SEPARATION:
# - llm.model_name: For text cleaning (use regular Gemini models)
# - tts.gemini.model_name: For audio generation (use -tts models)
# 
# PIPER VOICE OPTIONS:
# - en_US-ryan-high/medium: US Male voice
# - en_GB-cori-high: GB Female voice  
# - en_GB-alba-medium: GB Female voice
#
# TTS ENGINE COMPARISON:
# - Piper: Fast, local, no API costs, basic SSML
# - Gemini: Slower, cloud, API costs, natural single voice delivery
#
# SIMPLIFIED ARCHITECTURE:
# - Single consistent voice throughout document (no persona switching)
# - Shared TextSegmenter utilities for universal text processing
# - Engine-specific optimizations (rate limiting, audio formats)